
name: website deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get vars
        id: vars
        run: |
          echo "::set-output name=name::${GITHUB_REF#refs/*/}"
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      
      - name: deploy
        id: deployment
        uses: amondnet/vercel-action@v20
        if: github.ref != 'refs/heads/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./
          alias-domains: |
            dev.mketz.io
            ${{ steps.vars.outputs.sha }}.dev.mketz.io
      
      - name: deploy
        id: deployment
        uses: amondnet/vercel-action@v20
        if: github.ref = 'refs/heads/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-args: '--prod'
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./
          alias-domains: |
            www.mketz.io
            dev.mketz.io
            ${{ steps.vars.outputs.sha }}.dev.mketz.io

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        if: github.ref != 'refs/heads/main'
        with:
          runs: 10
          urls: |
            https://dev.mketz.io/
            https://dev.mketz.io/rezepte
            https://dev.mketz.io/rezept/burger-buns
          serverBaseUrl: ${{ secrets.LHCI_SERVER_URL }}
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        if: github.ref == 'refs/heads/main'
        with:
          runs: 10
          urls: |
            https://www.mketz.io/
            https://dev.mketz.io/rezepte
            https://dev.mketz.io/rezept/burger-buns
          serverBaseUrl: ${{ secrets.LHCI_SERVER_URL }}
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}